replicaCount: 1

image:
  repository: ghcr.io/your-org/git-proxy
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 9999

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: git-proxy.theia.artemis.cit.tum.de
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: git-proxy-tls
      hosts:
        - git-proxy.theia.artemis.cit.tum.de

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}
tolerations: []
affinity: {}
